[JENKINS-32801] implements SimpleBuildStep
jenkinsci/zephyr-for-jira-test-management-plugin pull request #2
Opened 2016-02-09 22:44 UTC by kuisathaverat

It adds compatibility with Pipeline plugin, now you can run a step of Zephyr fro jita test management plugin.

> 
node {
  git url: 'file:////Users/inifc/Documents/workspace/statusCheck'
  def mvnHome = tool 'maven3'
  sh "${mvnHome}/bin/mvn clean package"
  step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
  step([$class: 'ZfjReporter',serverAddress: 'http://127.0.0.1:9090',projectKey:'PRJ',versionKey:'1',cycleKey:'CreateNewCycle',cycleDuration:'30 days',cyclePrefix:''])
}

@reviewbybees

2016-02-09 22:45 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2016-02-15 10:13 UTC, amuniz commented on src/main/java/com/thed/zephyr/jenkins/reporter/ZfjReporter.java
> +    private static final String VERIFY_THE_JOB_CONFIGURATION = "Cannot Proceed. Please verify the job configuration";
Why did you add this constants? It's weird to use constants for log messages, if the same message is used repeatedly you can just add a log method (i.e. `logSurefireError()`, `logJobConfigurationError()`, etc)

2016-02-15 10:27 UTC, amuniz commented
LGTM. I just miss a pipeline specific test (there are examples in - almost - all plugins pipeline-compatible, for example [here](https://github.com/jenkinsci/findbugs-plugin/blob/4b429d04284200a4740b02e530289050489eb2fb/plugin/src/test/java/hudson/plugins/findbugs/workflow/WorkflowCompatibilityTest.java#L30))

2016-06-08 08:51 UTC, kuisathaverat commented
@mohan-zephyr Could you evaluate to merge this pull request? It makes this plugin compatible with Pipeline Plugin and the new paradigm of Jenkins Pipeline-as-Code

2016-09-15 19:45 UTC, gregamb commented
@mohan-zephyr I second @kuisathaverat request :+1:

2017-01-24 09:38 UTC, ColaciPhotography commented
Hi there,
are there any plans on merging this pr somewhere son? Would be really great to have this feature... or is there a workaround ?
Greetings 
Felix

2017-04-07 12:56 UTC, zackpollard commented
+1 for getting this implemented @kuisathaverat there is now a merge conflict with the PR though

2017-04-09 19:16 UTC, oleg-nenashev approved these changes
Needs a merge conflict resolution, but 🐝 in general.
@reviewbybees done

2017-04-09 19:45 UTC, zackpollard commented
@oleg-nenashev I have resolved the merge conflicts in a PR I made to @kuisathaverat branch. So if he accepts that then they should fall through to this PR too :)

2017-04-10 08:26 UTC, kuisathaverat commented
@zackpollard I saw too many changes on your PR only to resolve a conflict on one file I will review the conflict and try to resolve it without too many changes

2017-04-10 08:30 UTC, zackpollard commented
@kuisathaverat That's because it's also PRing all of the changes that your branch doesn't have from the master branch in this repository. Once they get merged into this PR, you will no longer see any of the commits other than the merge

2017-04-10 08:46 UTC, oleg-nenashev requested changes
Seems the merge was not correct 🐛 
`Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/scratch/jenkins/workspace/plugins/zephyr-for-jira-test-management-plugin/src/main/java/com/thed/zephyr/jenkins/reporter/ZfjReporter.java:[375,26] error: cannot find symbol`

2017-04-10 08:47 UTC, zackpollard commented
@oleg-nenashev yea there's an issue with one of the new calls that didn't show up when I initially merged... Just looking into the fix now

2017-04-10 08:51 UTC, zackpollard commented
@oleg-nenashev @kuisathaverat These changes seem odd, they are under a "Temp commit" title https://github.com/jenkinsci/zephyr-for-jira-test-management-plugin/commit/42362605c999c3f1590d9f924441a54bc76a9736

2017-04-10 08:55 UTC, kuisathaverat commented
it is because it wants an AbstractBuild not a Run class

2017-04-10 08:57 UTC, zackpollard commented
@kuisathaverat Yea, however i'm not sure we can pipe that through to there. Looking at the Run class, I think the getNumber() from that should suffice for getting the build number. We shouldn't need the AbstractBuild

2017-04-10 09:01 UTC, kuisathaverat commented
@zackpollard me too, but I do not understand why it use getRootBuild for me does not have too much sense 

> public AbstractBuild<?,?> getRootBuild()
> Gets the nearest ancestor AbstractBuild that belongs to the root project of getProject() that dominates/governs/encompasses this build.
> Some projects (such as matrix projects, Maven projects, or promotion processes) form a tree of jobs, and still in some of them, builds of child projects are related/tied to that of the parent project. In such a case, this method returns the governing build.

2017-04-10 09:02 UTC, zackpollard commented
@kuisathaverat Yea i'm unsure why you'd want to go up to the root build, I think the exact equivalent for this of run would be `getProject().getNumber()` however maybe we should loop in the person who made those changes originally for context?

2017-04-11 08:56 UTC, zackpollard commented
Failure on the build due to findbugs task
[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.3:check (findbugs) on project zephyr-for-jira-test-management: failed with 53 bugs and 0 errors

2017-04-11 10:16 UTC, kuisathaverat commented
none of those are in ZfjReporter.java that it is the only file that was changed so I am not gonna to touch any other file

2017-04-11 10:20 UTC, zackpollard commented
Yep, so how do we proceed from here? 

Sent from MailDroid

-----Original Message-----
From: Ivan Fernandez Calvo <notifications@github.com>
To: jenkinsci/zephyr-for-jira-test-management-plugin <zephyr-for-jira-test-management-plugin@noreply.github.com>
Cc: Zack Pollard <zackpollard@ymail.com>, Mention <mention@noreply.github.com>
Sent: Tue, 11 Apr 2017 11:16
Subject: Re: [jenkinsci/zephyr-for-jira-test-management-plugin] [JENKINS-32801] implements SimpleBuildStep (#2)

none of those are in ZfjReporter.java that it is the only file that was changed so I am not gonna to touch any other file

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/jenkinsci/zephyr-for-jira-test-management-plugin/pull/2#issuecomment-293214483

2017-04-11 13:33 UTC, kuisathaverat commented
we could open another PR for the findbugs issues but I don't know if the maintainer will attend it because this was open for more than a year

2017-04-11 14:09 UTC, zackpollard commented
So what now then, considering the bugs found are not with this class, then surely this PR could proceed regardless?

2017-04-11 22:11 UTC, kuisathaverat commented
I made other PR to fix some of the findbugs findings https://github.com/jenkinsci/zephyr-for-jira-test-management-plugin/pull/3

2017-07-31 17:55 UTC, lbrigman124 commented
Outside of the failing tests, The code fails on my system when trying to process JUnit results.
Same plugin on the same system when running within a freestyle job works.
java.lang.NullPointerException
	at com.thed.zephyr.jenkins.reporter.ZfjReporter.perform(ZfjReporter.java:363)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:748)

2017-08-04 18:43 UTC, kuisathaverat commented
@lbrigman124 this PR does not pass the find bug checks https://jenkins.ci.cloudbees.com/job/plugins/job/zephyr-for-jira-test-management-plugin/23/ , there is another PR to fix these errors https://github.com/jenkinsci/zephyr-for-jira-test-management-plugin/pull/3 but probably both are really outdated after more than a year, the maintainer does not have interest on those PR me neither

2017-09-13 14:09 UTC, closed without merging

2017-09-20 21:34 UTC, Olegwitcher commented
Hello @kuisathaverat .
If I correctly understand comments - We are not planning to add this plugin to support list of Jenkins pipeline.  And for now - we don't have any ability trigger Zephyr through Jenkins step?

2017-09-21 12:55 UTC, kuisathaverat commented
It is in the maintainer roof, this PR is no longer valid to make it mergeable, we have to make a ton of fix related with findbugs and all the changes in the code since it was proposed.

2017-09-21 15:37 UTC, Olegwitcher commented
Thank you for answer , @kuisathaverat

2017-12-15 19:21 UTC, sameerb29 commented
is there any workaround to add zephyr for jira pipeline ??

2019-05-27 16:20 UTC, ChioSoCo commented
> is there any workaround to add zephyr for jira in Jenkins pipeline ??

hey, did you find a workaround for this?

2019-10-10 04:58 UTC, nishant041 commented
Any solution for this?

2020-01-21 12:54 UTC, sahil-zymr commented
Any updates on this issue?